# Generated by Django 5.1.7 on 2025-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pill_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('times_per_day', models.IntegerField()),
                ('need_to_refill', models.BooleanField(default=False)),
                ('time_of_day', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1)),
                ('perscribed_by', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
    ]
