# Generated by Django 5.1.7 on 2025-03-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_patient_medication_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='patients',
            new_name='patient',
        ),
    ]
