# Generated by Django 5.1.7 on 2025-03-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_patients_medication_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.patient'),
            preserve_default=False,
        ),
    ]
