# Generated by Django 5.1.7 on 2025-03-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_medication_patient_medication_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='aide',
            new_name='user',
        ),
    ]
